apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ritacloud23/cloud-native-taskapp
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'argocd-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
